# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Setup .NET core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: clean dependencies
      run: dotnet clean
      working-directory: C:\VG\Project\runner\actions-runner\_work\WebProject\WebProject
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: C:\VG\Project\runner\actions-runner\_work\WebProject\WebProject
      
    - name: Build solution
      run: dotnet build --configuration Release
      working-directory: C:\VG\Project\runner\actions-runner\_work\WebProject\WebProject
      
    - name: publish
      run: dotnet publish --configuration Release --output publish
      working-directory: C:\VG\Project\runner\actions-runner\_work\WebProject\WebProject

    - name: zip publish folder
      if: ${{ success() }}
      run: Compress-Archive -Path "C:\VG\Project\runner\actions-runner\_work\WebProject\WebProject\publish/*" -DestinationPath "C:/inetpub/gitaction/artifact/published.zip" -Force

    - name: stop specific iis website
      run: |
        $appPoolName = 'web-project'
        Import-Module WebAdministration
        Stop-WebAppPool -Name $appPoolName
        PowerShell -Command "Stop-Website -Name 'web-project'"
        Start-Sleep -Seconds 20

    - name: Unzip Artifact
      run: Expand-Archive -Path "C:/inetpub/gitaction/artifact/published.zip" -DestinationPath "C:/inetpub/wwwroot-web-project" -Force
    
    - name: stop specific iis website
      run: |
        Start-Sleep -Seconds 20
        $appPoolName = 'web-project'
        Import-Module WebAdministration
        Start-WebAppPool -Name $appPoolName
        PowerShell -Command "Start-Website -Name 'web-project'"
        
    


